# ============================== Filebeat Inputs ===============================
filebeat.inputs:
- type: log
  # This must be set to true to enable this input configuration.
  enabled: true

  # Paths to your log files. The wildcard '*' is used to harvest logs
  # from every user's specific sub-directory.
  paths:
    - 'C:\Logs\AppLogs\User-*\*.log'

  # ============================== JSON Parsing ================================
  # This section tells Filebeat how to decode your structured JSON logs.
  json:
    # keys_under_root: true is a best practice. It moves the JSON fields to the
    # top level of the event, e.g., 'log.level' instead of 'json.log.level'.
    keys_under_root: true
    # add_error_key: true is for resilience. If a line is not valid JSON,
    # it won't be dropped; instead, it will be sent with an error flag.
    add_error_key: true
    # overwrite_keys: true ensures that fields in your log (like @timestamp)
    # will overwrite any default fields Filebeat might add.
    overwrite_keys: true

  # ============================ Performance Tuning ============================
  # How often Filebeat checks for new changes to files.
  # Lower values mean lower latency but slightly higher CPU usage. 3s is a good balance.
  scan_frequency: 3s

  # Keep file handles open for this duration after the last log event.
  # Since your NLog config closes the file after each write, this prevents
  # Filebeat from constantly opening/closing handles.
  close_inactive: 2h

  # The backoff settings control how Filebeat behaves when it can't find a file.
  # These are sensible defaults to prevent disk thrashing.
  backoff: 1s
  max_backoff: 10s


# ============================== Filebeat Output ===============================
# This section configures where to send the harvested logs.
# This example uses Elasticsearch. You could also use Logstash.
output.elasticsearch:
  # The addresses of your Elasticsearch cluster.
  hosts: ["https://my-elastic-cluster:9200"]

  # Use API Key or username/password for authentication.
  # It is highly recommended to use the Keystore to store these secrets securely.
  # Example:
  #   filebeat keystore add ES_USER
  #   filebeat keystore add ES_PASS
  username: "${ES_USER}"
  password: "${ES_PASS}"

# ================================== Logging ===================================
# Configure Filebeat's own logging.
logging.level: info
logging.to_files: true
logging.files:
  path: C:\ProgramData\filebeat\logs
  name: filebeat
  keepfiles: 7
  permissions: 0644